---
title: "Example_Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example_Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(inteRact)
library(tidyverse)
library(here)
```

Step 1: Load data, select events

```{r}

#get US 2015 dictionary
us_2015 <- epa_subset(dataset = "usfullsurveyor2015")

#make a dataframe of events 
set.seed(129)
events <- tibble(actor = sample(us_2015$term[us_2015$component == "identity"], 50),
                 behavior = sample(us_2015$term[us_2015$component == "behavior"], 50),
                 object = sample(us_2015$term[us_2015$component == "identity"], 50))


head(events)
```

Step 2: run some calculations on the dataframe! 

If you have a df already set with your events -- you can format your code like this to calculate the deflection and get the optimal behavior for each Actor - Behavior - Object row. 

```{r}

events %>% 
          rowwise() %>% 
          mutate(deflection = get_deflection(actor, behavior, object, 
                                             dictionary_key = "usfullsurveyor2015",
                                             gender = "average",
                                             equation_key = "us2010"),
                 opt_beh = list(optimal_behavior(actor, behavior, object, 
                                             dictionary_key = "usfullsurveyor2015",
                                             gender = "average",
                                             equation_key = "us2010", which = "both"))) %>% 
          unnest(opt_beh) %>% head(10)

```

or if you only want predictions for actor/behavior --
```{r}

act_events <- events %>% 
          rowwise() %>% 
          mutate(deflection = get_deflection(actor, behavior, object, 
                                             dictionary_key = "usfullsurveyor2015",
                                             gender = "average",
                                             equation_key = "us2010"),
                 opt_beh = list(optimal_behavior(actor, behavior, object, 
                                             dictionary_key = "usfullsurveyor2015",
                                             gender = "average",
                                             equation_key = "us2010", which = "actor"))) %>% 
  unnest(opt_beh)

act_events %>% 
          head(10)
```
You can also search for the closest behavior to the opt_behavior: 
```{r}
act_events <- act_events %>% 
              rowwise() %>% 
              mutate(closest_beh = closest_term(e = opt_E,
                                                p = opt_P,
                                                a = opt_A,
                                                dictionary_key = "usfullsurveyor2015",
                                                gender = "average",
                                                term_typ = "behavior",
                                                max_dist = 1,
                                                num_terms = 1))

act_events %>% unnest(closest_beh) %>% head()


```

